---
- name: install brew package
  homebrew:
    name: kubernetes-helm
    state: present
    options: force-bottle

- name: brew link package
  homebrew:
    name: kubernetes-helm
    state: linked
    options: overwrite
