---
- name: install brew package
  homebrew:
    name: kubernetes-helm
    state: present

- name: brew link package
  homebrew:
    name: kubernetes-helm
    state: linked
    options: overwrite, force
