---
- name: install brew package
  homebrew:
    name: kubernetes-helm
    state: present
- name: (re)link brew package
  block: 
  - homebrew:
      name: kubernetes-helm
      state: unlinked

  - homebrew:
      name: kubernetes-helm
      state: linked
      options: overwrite
